global:
  storageClass: managed-csi-premium

# https://hub.docker.com/r/bitnami/redis/tags
image:
  tag: 7.0.13-debian-11-r26

auth:
  enabled: true

replica:
  replicaCount: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m

sentinel:
  enabled: true
  masterSet: ex-dev
  downAfterMilliseconds: 5000
  failoverTimeout: 60000
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 100m
